apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: custom-template-github
  title: Custom Template Github
  description: Template for custom input on github for backstage
  tags:
    - test
spec:
  owner: group:backstage-nagarro
  type: website
  brand: Vauto
  portfolio: I5
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - slack_url
        - language
        - team_name
        - engineering_manager
        - carts
        - product_name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
                 
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User

        slack_url:
          title: Slack
          type: string
          description: Slack group url
          ui:placeholder: E.g. https://slack.com/signin#/signin

        language:
          title: language
          type: string
          description: Programming language
          ui:placeholder: E.g. Java, Python

        team_name:
          title: Team
          type: string
          description: Team Name
          ui:placeholder: Enter your team name

        engineering_manager:
          title: Engineering Manager
          type: string
          description: Engineering Manager
          ui:placeholder: Enter your manager name

        carts:
          title: Carts
          type: string
          enum: ["VIP", "VIM"]

        product_name:
          title: Product Name
          type: string
          description: Product Name
          ui:placeholder: E.g. Provision
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          slack_url: ${{ parameters.slack_url }}
          language: ${{ parameters.language }}
          engineering_manager: ${{ parameters.engineering_manager }}
          carts: ${{ parameters.carts }}
          product_name: ${{ parameters.product_name }}
          team_name: ${{ parameters.team_name }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"        
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
